-- Bloom CRM 5.0 esquema privado
create extension if not exists pgcrypto;

create table if not exists bloom_empresas (id text primary key, owner_id uuid not null references auth.users(id) on delete cascade, nombre text, empresa text, sector text, estado text, tipo text, fecha date, fecha_proxima date, carpeta text, data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
alter table bloom_empresas enable row level security;
drop policy if exists "owner select" on bloom_empresas; drop policy if exists "owner insert" on bloom_empresas; drop policy if exists "owner update" on bloom_empresas; drop policy if exists "owner delete" on bloom_empresas;
create policy "owner select" on bloom_empresas for select to authenticated using (owner_id = auth.uid());
create policy "owner insert" on bloom_empresas for insert to authenticated with check (owner_id = auth.uid());
create policy "owner update" on bloom_empresas for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner delete" on bloom_empresas for delete to authenticated using (owner_id = auth.uid());
create table if not exists bloom_alumnos (id text primary key, owner_id uuid not null references auth.users(id) on delete cascade, nombre text, empresa text, sector text, estado text, tipo text, fecha date, fecha_proxima date, carpeta text, data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
alter table bloom_alumnos enable row level security;
drop policy if exists "owner select" on bloom_alumnos; drop policy if exists "owner insert" on bloom_alumnos; drop policy if exists "owner update" on bloom_alumnos; drop policy if exists "owner delete" on bloom_alumnos;
create policy "owner select" on bloom_alumnos for select to authenticated using (owner_id = auth.uid());
create policy "owner insert" on bloom_alumnos for insert to authenticated with check (owner_id = auth.uid());
create policy "owner update" on bloom_alumnos for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner delete" on bloom_alumnos for delete to authenticated using (owner_id = auth.uid());
create table if not exists bloom_convenios (id text primary key, owner_id uuid not null references auth.users(id) on delete cascade, nombre text, empresa text, sector text, estado text, tipo text, fecha date, fecha_proxima date, carpeta text, data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
alter table bloom_convenios enable row level security;
drop policy if exists "owner select" on bloom_convenios; drop policy if exists "owner insert" on bloom_convenios; drop policy if exists "owner update" on bloom_convenios; drop policy if exists "owner delete" on bloom_convenios;
create policy "owner select" on bloom_convenios for select to authenticated using (owner_id = auth.uid());
create policy "owner insert" on bloom_convenios for insert to authenticated with check (owner_id = auth.uid());
create policy "owner update" on bloom_convenios for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner delete" on bloom_convenios for delete to authenticated using (owner_id = auth.uid());
create table if not exists bloom_documentos (id text primary key, owner_id uuid not null references auth.users(id) on delete cascade, nombre text, empresa text, sector text, estado text, tipo text, fecha date, fecha_proxima date, carpeta text, data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
alter table bloom_documentos enable row level security;
drop policy if exists "owner select" on bloom_documentos; drop policy if exists "owner insert" on bloom_documentos; drop policy if exists "owner update" on bloom_documentos; drop policy if exists "owner delete" on bloom_documentos;
create policy "owner select" on bloom_documentos for select to authenticated using (owner_id = auth.uid());
create policy "owner insert" on bloom_documentos for insert to authenticated with check (owner_id = auth.uid());
create policy "owner update" on bloom_documentos for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner delete" on bloom_documentos for delete to authenticated using (owner_id = auth.uid());
create table if not exists bloom_carpetas (id text primary key, owner_id uuid not null references auth.users(id) on delete cascade, nombre text, empresa text, sector text, estado text, tipo text, fecha date, fecha_proxima date, carpeta text, data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
alter table bloom_carpetas enable row level security;
drop policy if exists "owner select" on bloom_carpetas; drop policy if exists "owner insert" on bloom_carpetas; drop policy if exists "owner update" on bloom_carpetas; drop policy if exists "owner delete" on bloom_carpetas;
create policy "owner select" on bloom_carpetas for select to authenticated using (owner_id = auth.uid());
create policy "owner insert" on bloom_carpetas for insert to authenticated with check (owner_id = auth.uid());
create policy "owner update" on bloom_carpetas for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner delete" on bloom_carpetas for delete to authenticated using (owner_id = auth.uid());
create table if not exists bloom_seguimientos (id text primary key, owner_id uuid not null references auth.users(id) on delete cascade, nombre text, empresa text, sector text, estado text, tipo text, fecha date, fecha_proxima date, carpeta text, data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
alter table bloom_seguimientos enable row level security;
drop policy if exists "owner select" on bloom_seguimientos; drop policy if exists "owner insert" on bloom_seguimientos; drop policy if exists "owner update" on bloom_seguimientos; drop policy if exists "owner delete" on bloom_seguimientos;
create policy "owner select" on bloom_seguimientos for select to authenticated using (owner_id = auth.uid());
create policy "owner insert" on bloom_seguimientos for insert to authenticated with check (owner_id = auth.uid());
create policy "owner update" on bloom_seguimientos for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner delete" on bloom_seguimientos for delete to authenticated using (owner_id = auth.uid());
create table if not exists bloom_email_templates (id text primary key, owner_id uuid not null references auth.users(id) on delete cascade, nombre text, empresa text, sector text, estado text, tipo text, fecha date, fecha_proxima date, carpeta text, data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
alter table bloom_email_templates enable row level security;
drop policy if exists "owner select" on bloom_email_templates; drop policy if exists "owner insert" on bloom_email_templates; drop policy if exists "owner update" on bloom_email_templates; drop policy if exists "owner delete" on bloom_email_templates;
create policy "owner select" on bloom_email_templates for select to authenticated using (owner_id = auth.uid());
create policy "owner insert" on bloom_email_templates for insert to authenticated with check (owner_id = auth.uid());
create policy "owner update" on bloom_email_templates for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner delete" on bloom_email_templates for delete to authenticated using (owner_id = auth.uid());
create table if not exists bloom_actividad (id text primary key, owner_id uuid not null references auth.users(id) on delete cascade, nombre text, empresa text, sector text, estado text, tipo text, fecha date, fecha_proxima date, carpeta text, data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
alter table bloom_actividad enable row level security;
drop policy if exists "owner select" on bloom_actividad; drop policy if exists "owner insert" on bloom_actividad; drop policy if exists "owner update" on bloom_actividad; drop policy if exists "owner delete" on bloom_actividad;
create policy "owner select" on bloom_actividad for select to authenticated using (owner_id = auth.uid());
create policy "owner insert" on bloom_actividad for insert to authenticated with check (owner_id = auth.uid());
create policy "owner update" on bloom_actividad for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner delete" on bloom_actividad for delete to authenticated using (owner_id = auth.uid());
insert into storage.buckets (id,name,public) values ('bloom-crm-documents','bloom-crm-documents',false) on conflict (id) do update set public=false;
drop policy if exists "private read documents" on storage.objects;drop policy if exists "private upload documents" on storage.objects;drop policy if exists "private update documents" on storage.objects;drop policy if exists "private delete documents" on storage.objects;
create policy "private read documents" on storage.objects for select to authenticated using (bucket_id='bloom-crm-documents' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "private upload documents" on storage.objects for insert to authenticated with check (bucket_id='bloom-crm-documents' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "private update documents" on storage.objects for update to authenticated using (bucket_id='bloom-crm-documents' and (storage.foldername(name))[1]=auth.uid()::text) with check (bucket_id='bloom-crm-documents' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "private delete documents" on storage.objects for delete to authenticated using (bucket_id='bloom-crm-documents' and (storage.foldername(name))[1]=auth.uid()::text);